controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

app_logout:
    path: /logout
    methods: GET

app_stations:
    path: /stations/{location}
    controller: App\Controller\StationController::index

app_redirect:
    path: /stations
    controller: App\Controller\StationController::redirection